#!/usr/bin/env node
/**
 * THE SEVEN DOCUMENTS, GENERATED.
 *
 * The frontend charter names seven references and requires them read
 * before any route, data view or provenance interaction is designed.
 * They did not exist. Hand-writing them would have produced seven
 * documents restating shared/planes.mjs, shared/apis.mjs,
 * shared/platform.mjs and shared/ecosystem.mjs in prose - and prose
 * that restates a register drifts from it, usually within a day, and
 * then nobody can tell which is stale.
 *
 * This ecosystem already reached that conclusion and recorded it as a
 * convergence: doctrine that restates code is GENERATED from it, so it
 * cannot drift. So these are generated, and `npm run check` regenerates
 * and diffs - a document edited by hand fails the chain the way a
 * stale lockfile would.
 *
 * TWO KINDS OF CONTENT, marked in every file:
 *
 *   MEASURED  read from the registers at generation time. Counts,
 *             assignments, statuses, presence. Never typed by hand.
 *   AUTHORED  a decision or a rule, which no register can derive. It
 *             lives in this file, so there is still exactly one source.
 *
 * SCOPE. These describe THIS twin - the Payload Render Engine, a
 * read-only projection - and say so on every page. They are not a
 * description of a deployed Caravan, Tradewind or Landshark service,
 * and nothing here should be read as evidence that one exists.
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { registerRoutes } from '../server/api.mjs';
import { PLANES, MODULE_FAMILIES, ROUTE_PLANES, planeCoverage, planeOf, LIMB_INVARIANT, INVARIANT_ID, INVARIANT_EXTENSION } from '../shared/planes.mjs';
import { APIS, PRODUCT_HIERARCHY, STREAM_OWNERS, streamCoverage, ownerOf } from '../shared/apis.mjs';
import { PLATFORM_LAYERS, FIRST_FOOTPRINT, DEFERRED_BY_DECISION, countLayers } from '../shared/platform.mjs';
import { APPARATUSES, LIFECYCLE, CONVERGENCES, DIVERGENCES } from '../shared/ecosystem.mjs';
import { LIMB_KINDS, NON_SUCCESS_STATES } from '../shared/envelope.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const routes = await registerRoutes();
const patterns = routes.map((r) => r.pattern.source.replace(/^\^|\$$/g, '').replace(/\\\//g, '/'));
const planes = planeCoverage(patterns);
const streams = streamCoverage(patterns);

const HEAD = (title, purpose, sources) => `<!--
  GENERATED by scripts/gen-docs.mjs - do not edit by hand.
  \`npm run check\` regenerates this file and fails if it differs.
  Read from: ${sources.join(', ')}
-->

# ${title}

${purpose}

**Scope.** This describes the Payload Render Engine - a read-only
projection over a corpus it does not own. It is not a description of a
deployed Caravan, Tradewind or Landshark service, and nothing here is
evidence that one exists.

**MEASURED** sections are read from the registers when this file is
generated. **AUTHORED** sections are decisions, and live in the
generator so there is still one source.
`;

const table = (headers, rows) =>
  [`| ${headers.join(' | ')} |`, `| ${headers.map(() => '---').join(' | ')} |`, ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n');

const files = {};

// ------------------------------------------------------------ 1. AGENTS
files['AGENTS.md'] = `${HEAD(
  'AGENTS.md - whole-project coherence',
  'How anyone working in this repository - person or agent - keeps it coherent with the ecosystem around it.',
  ['shared/planes.mjs', 'shared/apis.mjs', 'shared/ecosystem.mjs']
)}
## AUTHORED - the rules that do not come from a register

1. **Measure, do not assert.** Every claim this repository makes about
   itself is checked. A register that says a thing is present must name
   where that was read from, and a check must fail when it is not.
2. **Absence is never zero.** Anything unknown is ABSENT with a reason
   and a remedy. A blank, a zero, or a silent fallback is a defect.
3. **Prove the check bites.** A check is not finished until a planted
   violation makes it fail by name. A check that cannot fail is worse
   than no check, because it reads as coverage.
4. **The renderer is never authoritative.** A derived representation may
   not mutate the state it derives from. Held by \`scripts/check-seam.mjs\`
   and, from the other end, by GET-only transport.
5. **Scope every claim.** "In this service" and "in the program" are
   different statements. A register that reports only the first will
   tell another team their work does not exist.
6. **One source per fact.** Doctrine that restates code is generated
   from it. These seven documents are generated for that reason.

## MEASURED - what is in this repository now

${table(
  ['Register', 'Holds', 'Rows'],
  [
    ['`shared/planes.mjs`', 'the four planes, module families, route assignments', String(Object.keys(ROUTE_PLANES).length)],
    ['`shared/apis.mjs`', 'the three products and which stream powers which', String(Object.keys(STREAM_OWNERS).length)],
    ['`shared/platform.mjs`', 'the six data-platform layers, both scopes', String(PLATFORM_LAYERS.length)],
    ['`shared/ecosystem.mjs`', 'the apparatus register', String(APPARATUSES.length)],
    ['`shared/envelope.mjs`', 'the truth-response limbs', String(LIMB_KINDS.length)],
    ['`shared/notation.mjs`', 'the notation:// identity space', 'kinds'],
  ]
)}

Checks in the chain: \`check-seam\`, \`check-security\`, \`check-ecosystem\`,
\`check-planes\`, \`validate-provenance\`, \`check-sea-lanes\`, \`test-miner\`,
\`server/test.mjs\`, \`tsc --noEmit\`.

## AUTHORED - before you add a surface

Identify, in this order: which **product** owns it (\`shared/apis.mjs\`),
which **plane** it sits in (\`shared/planes.mjs\`), and which **limb** its
answer carries (\`shared/envelope.mjs\`). All three are declared before
the code, and the checks hold the code to the declaration.
`;

// --------------------------------------------------- 2. PROJECT_CONTEXT
files['PROJECT_CONTEXT.md'] = `${HEAD(
  'PROJECT_CONTEXT.md - roadmap and current state',
  'What exists today, and what has to be true before the next thing is claimed.',
  ['shared/apis.mjs', 'shared/platform.mjs']
)}
## MEASURED - the product bundle today

${PRODUCT_HIERARCHY.ecosystem}
- **${PRODUCT_HIERARCHY.bundle.label}** - ${streams.byApi['payload-os'].total} shared streams. Public API: \`${PRODUCT_HIERARCHY.bundle.isPublicApi}\`.

${table(
  ['Product', 'Streams', 'Core', 'Context', 'Status'],
  APIS.map((a) => {
    const c = streams.byApi[a.id];
    return [`**${a.label}**`, String(c.total), String(c.core), String(c.context), `\`${a.status}\``];
  })
)}

Every served stream is assigned: **${streams.assigned}/${streams.total}**, with
${streams.unassigned.length} unassigned and ${streams.stale.length} stale.

${APIS.filter((a) => streams.byApi[a.id].total === 0)
  .map((a) => `> **${a.label} is ABSENT.** ${a.reason}\n>\n> Unblocked by: ${a.unblockedBy}`)
  .join('\n\n')}

## MEASURED - the data platform beneath it

${table(
  ['#', 'Layer', 'Here', 'Held in the program by'],
  PLATFORM_LAYERS.map((l) => [String(l.ordinal), l.label.split(' - ')[0], `\`${l.presence}\``, l.ecosystem?.holder ?? '-'])
)}

First production footprint: **${countLayers().footprintPresent} of ${countLayers().footprintTotal}** present.

Deferred by decision, so none is added quietly: ${DEFERRED_BY_DECISION.map((d) => `\`${d.id}\``).join(', ')}.

## AUTHORED - the order

1. **Caravan is the first slice.** It is the only product with streams,
   and the only one whose claims this twin can currently back.
2. **Tradewind stays a shell** until it has its own source, release,
   rights and customer-service evidence. Four market streams that are
   honest about being single-venue readings are not a released product.
3. **Landshark opens when a parcel source does.** Not before. A
   facility point is not a parcel.
4. **Payload OS is never sold.** It is the layer the three stand on.
`;

// ------------------------------------------------ 3. PAYLOAD_API_PRODUCT
files['docs/PAYLOAD_API_PRODUCT.md'] = `${HEAD(
  'Payload OS - the bundle boundary',
  'What Payload OS is, what it holds, and why it is not a fourth API.',
  ['shared/apis.mjs', 'shared/planes.mjs']
)}
## AUTHORED - the boundary

${PRODUCT_HIERARCHY.bundle.rule}

${PRODUCT_HIERARCHY.bundle.holds.replace(/^the /, 'It holds the ')}.

**Legacy names.** ${PRODUCT_HIERARCHY.bundle.legacyNames}

## MEASURED - the shared streams

${streams.byApi['payload-os'].total} streams stand under all three products.

${table(
  ['Stream', 'Carries', 'Plane', 'Limb'],
  Object.entries(STREAM_OWNERS)
    .filter(([, v]) => v.api === 'payload-os')
    .map(([k, v]) => [`\`${k}\``, v.stream, planeOf(k)?.plane ?? '-', `\`${planeOf(k)?.limb ?? '-'}\``])
)}

## MEASURED - the module families it covers

${table(
  ['Family', 'Role', 'Presence'],
  MODULE_FAMILIES.map((f) => [f.family, `\`${f.role}\``, `\`${f.presence}\``])
)}
`;

// ------------------------------------------------ 4. CARAVAN_API_PRODUCT
{
  const caravan = APIS.find((a) => a.id === 'caravan');
  const rows = Object.entries(STREAM_OWNERS).filter(([, v]) => v.api === 'caravan');
  files['docs/CARAVAN_API_PRODUCT.md'] = `${HEAD(
    'Caravan API - the first wedge',
    caravan.task,
    ['shared/apis.mjs']
  )}
## AUTHORED - what it is and is not

**Job:** ${caravan.job}. **Not the job:** ${caravan.notTheJob}.

Object classes: ${caravan.objectClasses.map((c) => `\`${c}\``).join(', ')}.

It refuses:

${caravan.refuses.map((r) => `- ${r}`).join('\n')}

### Core versus context

A \`core\` stream is a record of Caravan's own object class. A \`context\`
stream informs it without being one. The distinction is load-bearing:
an aircraft track is not a shipment, and a wildfire is not a delay. A
view that renders context as core invents a consignment nobody shipped.

## MEASURED - the streams

**${rows.filter(([, v]) => v.role === 'core').length} core**

${table(
  ['Stream', 'Carries', 'Limb'],
  rows.filter(([, v]) => v.role === 'core').map(([k, v]) => [`\`${k}\``, v.stream, `\`${planeOf(k)?.limb ?? '-'}\``])
)}

**${rows.filter(([, v]) => v.role === 'context').length} context** - informs the slice, is not a record in it

${table(
  ['Stream', 'Carries', 'Limb'],
  rows.filter(([, v]) => v.role === 'context').map(([k, v]) => [`\`${k}\``, v.stream, `\`${planeOf(k)?.limb ?? '-'}\``])
)}

## MEASURED - the migration boundary

The spine the three products would share is \`organization\`, \`site\`,
\`commodity\` and \`contract\`. Measured against the corpus this twin
serves: **site** is a first-class entity, **commodity** exists and is
thin, **organization** is a string field on facilities rather than a
record, and **contract** is a field rather than a type. Until
organization and contract are entities, the cross-product join cannot
be expressed and Caravan is a single-product corpus.
`;
}

// ---------------------------------------------------- 5. API_SURFACE
files['docs/API_SURFACE.md'] = `${HEAD(
  'API surface - the authorized planes',
  'Every served route, the plane that admits it, the limb its answer carries, and the product that owns it.',
  ['shared/planes.mjs', 'shared/apis.mjs', 'shared/envelope.mjs']
)}
## AUTHORED - the invariant

> **${INVARIANT_ID}.** ${LIMB_INVARIANT}

**This twin is a superset of the bundle's ${INVARIANT_EXTENSION.base}.** As the
ecosystem states it, the invariant has two limbs
(${INVARIANT_EXTENSION.baseLimbs.map((l) => `\`${l}\``).join(', ')}). This
surface adds \`${INVARIANT_EXTENSION.addedHere}\`, because
${INVARIANT_EXTENSION.why} ${INVARIANT_EXTENSION.proposeUpstream}

Three independent facts travel with every route. None is derivable from
the others, and \`API-004\` fails if they ever collapse.

## MEASURED - the four planes

${table(
  ['#', 'Plane', 'Serves', 'Routes'],
  PLANES.map((p) => [String(p.ordinal), `\`${p.id}\``, p.serves, String(planes.byPlane[p.id] ?? 0)])
)}

${PLANES.filter((p) => p.presence === 'ABSENT')
  .map((p) => `> **${p.label} is declared and empty.** ${p.reason}`)
  .join('\n\n')}

## MEASURED - the truth-response classification

${table(['Limb', 'Field', 'Count'], LIMB_KINDS.map((k) => [`\`${k}\``, `\`meta.${{ CANONICAL_PROOF: 'reference', VERIFIED_DERIVATION: 'derivation', OPERATIONAL_OBSERVATION: 'observation' }[k]}\``, String(planes.byLimb[k] ?? 0)]))}

Typed non-success states, which a view must keep visible:

${table(['State', 'Means'], NON_SUCCESS_STATES.map((s) => [`\`${s.id}\``, s.means]))}

## MEASURED - every route

${table(
  ['Route', 'Plane', 'Limb', 'Product'],
  patterns.sort().map((p) => {
    const pl = planeOf(p);
    const ow = ownerOf(p);
    return [`\`${p}\``, pl?.plane ?? '**unassigned**', `\`${pl?.limb ?? '-'}\``, ow?.api ?? '**unassigned**'];
  })
)}
`;

// -------------------------------------------- 6. CONTROL_PLANE_UNIVERSE
files['docs/CONTROL_PLANE_UNIVERSE.md'] = `${HEAD(
  'Control Plane - the safe visual contract',
  'What a frontend may render from the governance plane, and what it must never invent.',
  ['shared/planes.mjs', 'shared/platform.mjs']
)}
## AUTHORED - the visual contract

1. **Logical topology only.** The control plane is not geographic. Do
   not add coordinates. A geographic map requires separately authorized
   WGS84 spatial data, and absent that the honest rendering is a graph.
2. **No raw security detail.** Authority is rendered PRESENT or ABSENT,
   never as a value. Host and network topology, resolvers and
   deployment controls never reach the browser.
3. **Verified transitions only.** Show chronological transitions that
   were recorded. Do not synthesize history from a missing snapshot - a
   gap is drawn as a gap.
4. **Proportional affordances.** Read, compare, filter and inspect. No
   control that changes corpus, rights, release or infrastructure state.
5. **A drill-down is a new authorization.** A provenance path may not be
   turned into a raw-data request from an id or digest alone.
6. **An unknown that looks good is still unknown.** State labels and
   limitation badges come before visual treatment.

## MEASURED - what the governance plane actually serves

${table(
  ['Route', 'Carries', 'Limb'],
  Object.entries(ROUTE_PLANES)
    .filter(([, v]) => v.plane === 'governance')
    .map(([k, v]) => [`\`${k}\``, ownerOf(k)?.stream ?? '-', `\`${v.limb}\``])
)}

## MEASURED - stated limitations a view must render

${Object.entries(ROUTE_PLANES)
  .filter(([, v]) => v.plane === 'governance' && (v.limitations ?? []).length)
  .map(([k, v]) => `**\`${k}\`**\n\n${v.limitations.map((l) => `- ${l}`).join('\n')}`)
  .join('\n\n')}
`;

// ------------------------------------------- 7. NOTATION_SYSTEMS_ECOSYSTEM
files['NOTATION_SYSTEMS_ECOSYSTEM.md'] = `${HEAD(
  'Notation Systems - architecture and terminology',
  'The apparatuses, the corpus lifecycle they span, and the rules they arrived at independently.',
  ['shared/ecosystem.mjs', 'shared/platform.mjs']
)}
## MEASURED - the apparatuses

${table(
  ['Apparatus', 'Presence', 'Stages', 'Basis'],
  APPARATUSES.map((a) => [`**${a.label}**`, `\`${a.presence}\``, a.stages.join(', ') || '-', a.presenceBasis ?? '-'])
)}

## MEASURED - the corpus lifecycle

${LIFECYCLE.map((s, i) => `${i + 1}. **${s.label}** - ${s.question}`).join('\n')}

## MEASURED - what the apparatuses agree on, independently

${CONVERGENCES.map((c) => `### ${c.statement}\n\nSeen in: ${c.seenIn.map((s) => `\`${s}\``).join(', ')}.\n\n${c.evidence}`).join('\n\n')}

## MEASURED - what they do not agree on

${DIVERGENCES.map(
  (d) =>
    `### ${d.statement}\n\n*Severity: ${d.severity}.* Owned by **${d.ownedBy}**.\n\n` +
    `${(d.detail ?? []).map((x) => `- ${x}`).join('\n')}\n\n` +
    `**Why it matters.** ${d.whyItMatters}\n\n**Proposal.** ${d.proposal}`
).join('\n\n')}

## AUTHORED - terminology

- **Apparatus** - a repository that holds one stage of the corpus lifecycle.
- **Corpus** - a versioned, committed set of records with a proof root.
- **Projection** - a rebuildable read over a corpus. Never authoritative.
- **Limb** - which of the three kinds an answer is.
- **Plane** - who may read a route, and under what promise.
- **Product** - which of the three APIs owns a stream.
`;

// ---------------------------------------------------------------- emit
const CHECK = process.argv.includes('--check');
let drift = 0;
for (const [rel, content] of Object.entries(files)) {
  const path = join(ROOT, rel);
  mkdirSync(dirname(path), { recursive: true });
  const existing = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (CHECK) {
    if (existing !== content) {
      drift += 1;
      console.error(`  DRIFT ${rel}${existing === null ? ' (missing)' : ''}`);
    } else {
      console.log(`  ok   ${rel}`);
    }
  } else {
    writeFileSync(path, content);
    console.log(`  ${existing === content ? 'unchanged' : 'written  '} ${rel}`);
  }
}
if (CHECK && drift) {
  console.error(`\nDOC DRIFT - ${drift} of ${Object.keys(files).length} generated documents differ from the registers.`);
  console.error('REMEDY: run `node scripts/gen-docs.mjs` and commit the result. These files are generated so they cannot drift from the code they describe; editing one by hand is the drift this check exists to catch.');
  process.exit(1);
}
console.log(`\n${CHECK ? 'DOCS IN SYNC' : 'DOCS GENERATED'} - ${Object.keys(files).length} documents`);
